"""empty message

Revision ID: fa873968314e
Revises: bddd6feecec3
Create Date: 2020-11-02 22:34:13.709032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa873968314e'
down_revision = 'bddd6feecec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creater',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('extras', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creater_name'), 'creater', ['name'], unique=True)
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('people', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('recommend', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.Column('creater_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creater_id'], ['creater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_genre'), 'recipe', ['genre'], unique=False)
    op.create_index(op.f('ix_recipe_title'), 'recipe', ['title'], unique=False)
    op.drop_column('users', 'age')
    op.drop_column('users', 'height')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('height', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('age', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_recipe_title'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_genre'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_creater_name'), table_name='creater')
    op.drop_table('creater')
    # ### end Alembic commands ###
